name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Gemini-Local
    provider: openai
    model: gemini-3.1-pro-preview
    apiBase: https://vertex-cursor-proxy-190942156229.europe-north1.run.app/v1
    apiKey: vertex
    completionOptions:
      stream: false